MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:create, :edit, :show, :update, :destroy]

end

MusicApp/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint           not null, primary key
#  band_id    :integer          not null
#  year       :integer          not null
#  title      :string           not null
#  live       :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Album < ApplicationRecord
    validates :band_id, :year, :title, :live, presence: true

    belongs_to :band,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Band
end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicApp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Band < ApplicationRecord
    validates :name, presence: true

    has_many :albums,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Album
end

MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    after_initialize :ensure_session_token

    validates :email, :password_digest, :session_token, presence: true
    validates :email, :session_token, uniqueness: true
    validates :password, length: {minimum: 6}, allow_nil: true

    attr_reader :password

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        if user && user.is_password?(password)
            user
        else
            nil
        end
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def is_password?(password)
        password_obj = BCrypt::Password.new(self.password_digest)
        password_obj.is_password?(password)
    end

    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
    end
end

MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    def index
        @album = Album.all
        render :index
    end

    def show
        @album = Album.find(params[:id])
        render :show
    end

    def new
        @album = Album.new
        render :new
    end

    def create
        @album = Album.create(album_params)

        if @album.save
            flash[:sucess] = ["Successfully logged!"]
            redirect_to album_url(@album.id)
        else
            flash.now[:error] = @album.errors.full_messages
            render :new
        end
    end

    def edit

    end

    def update

    end

    def destroy
    end

    private
    def album_params
        params.require(:album).permit(:band_id, :year, :title, :live)
    end
end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(session_token:session[:session_token])
    end

    def logged_in?
        !!current_user
    end

    def logged_out!
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end

    def login(user)
        session[:session_token] = user.reset_session_token!
    end

    def require_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def require_logged_out
        redirect_to user_url(@current_user) if logged_in?
    end
end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def index
        @bands = Band.all 
        render :index
    end

    def show
        @band = Band.find(params[:id])
        render :show
    end

    def new
        @band = Band.new
        render :new
    end

    def create
        @band = Band.new(band_params)

        if @band.save
            flash[:errors] = ["Band has been added"]
            redirect_to band_url(@band.id)
        else
            flash.now[:errors] = ["Unsucesssful save"]
            render :new
        end
    end

    def edit
        @band = Band.find(params[:id])
        render :edit
    end

    def update
        @band = Band.find(params[:id])

        if @band.update(band_params)
            redirect_to band_url(@band.id)
        else
            render :edit
        end
    end

    def destroy
        @band = Band.find_by(params[:name])
        @band.destroy
        redirect_to bands_url
    end

    private
    def band_params
        params.require(:band).permit(:name)
    end
end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_logged_out, only: [:new, :create]
    before_action :require_logged_in, only: [:destroy]


    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.find_by_credentials(
            params[:user][:email],
            params[:user][:password]
        )

        if @user
            login(@user)
            redirect_to user_url(@user)
        else
            flash[:errors] = ["Invalid credentials"]
            render :new
        end
    end

    def destroy
        logged_out!
        redirect_to new_session_url
    end
end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_logged_in, only: [:show]
    before_action :require_logged_out, only: [:new, :create]

    def new
        @user = User.new
        render :new
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    def create
        @user = User.new(user_params)

        if @user.save
            login(@user)
            flash[:success] = ["Successful creation!"]
            redirect_to user_url(@user.id)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def user_params
        params.require(:user).permit(:email, :password, :session_token)
    end

end

MusicApp/app/helpers/albums_helper.rb
module AlbumsHelper
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
    def auth_token
        '<input
            type="hidden"
            name="authenticity_token"
            value="#{form_authenticity_token}"
        />'.html_safe
    end
end

MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

MusicApp/app/views/albums/new.html.erb
<h1>Add an Album</h1>

<form action="<%= albums_url %>" method="post">
    <%= auth_token %>
    <label>Year:
        <input type="text" name="album[year]">
    </label>
    <br>
    <label>Title:
        <input type="text" name="album[title]">
    </label>
    <br>
    <label>Recorded:
        <input type="radio" value="true">
        <label for="live" name="album[live] value="TRUE"></label>
        <input type="radio" value="false" checked>
        <label for="studio" name="album[live] value="FALSE"></label>
    </label>
    <br>
    <input type="submit" value="Add Album">
</form>

MusicApp/app/views/albums/show.html.erb
<h1>You are viewing <%= @album.title %></h1>
<ul>
    <p>Released: <%= @album.year %></p>
    <p>Recorded: <%= FALSE ? "In Studio" : "live" %></p>
<ul>

MusicApp/app/views/bands/edit.html.erb
<h1>Edit Band</h1>

<form action="<%= band_url %>" method="post">
    <input type="hidden" name="_method" value="patch">
    <%= auth_token %>
    <label>Name:
        <input type="text" name="band[name]" value="<%= @band.name %>">
    </label>

    <input type="submit" value="Edit">
</form>

MusicApp/app/views/bands/index.html.erb
<h1>Bands</h1>

<ul>
    <% @bands.each do |band| %>
    <li><%= band.name %></li>
    <% end %>
</ul>

MusicApp/app/views/bands/new.html.erb
<h1>Add a band</h1>

<form action="<%= bands_url %>" method="post">
    <%= auth_token %>
    <label>Name:
        <input type="text" name="band[name]">
    </label>

    <input type="submit" value="Add">
</form>

MusicApp/app/views/bands/show.html.erb
<h2>You are viewing <%= @band.name %>.</h2>

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>MUSIC APP:</h1>
      <h2>~FULLFILL ALL YOUR MUSIC INVENTORY NEEDS~</h2>
      <% if logged_in? %>
        <h2>Hello! <%= current_user.email %>!</h2>
        <form action="<%= session_url %>" method="post">
          <%= auth_token %>
          <input type="hidden" name="_method" value="delete">
          <input type="submit" value="Logout">
        </form>
      <% else %>
        <a href="<%= new_user_url %>">Sign Up</a>
        <a href="<%= new_session_url %>">Log In</a>
      <% end %>
    </header>
    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
      <p><%= error %></p>
      <% end %>
    <% end %>

    <% if flash[:success] %>
      <% flash[:success].each do |msg| %>
      <p><%= msg %></p>
      <% end %>
    <% end %>
    
    <%= yield %>

  </body>
</html>

MusicApp/app/views/users/new.html.erb
<h2>SIGN UP HERE:<h2>

<h3>
    <form action="<%= users_url %>" method="post">
        <%= auth_token %>
        <label>Email:
            <input type="email" name="user[email]" value="">
        </label>
        <br>
        <label>Password:
            <input type="password" name="user[password]" value="">
        </label>
        <br>
        <input type="submit" value="Create">
    </form>
</h3>

MusicApp/app/views/users/show.html.erb
<h2>Hope you find all your music needs, <%= @user.email %><h2>